/-
Copyright (c) 2026 Nelson Spence. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nelson Spence
-/
import Mathlib.Analysis.Calculus.ContDiff.Defs
import Mathlib.Analysis.Calculus.ContDiff.FTaylorSeries
import Mathlib.Geometry.Manifold.Diffeomorph
import Mathlib.Topology.MetricSpace.Pseudo.Basic
import Mathlib.Topology.Order.Compact

/-!
# The weak `C^n` topology on maps between manifolds

For manifolds `M` and `N`, the weak `C^n` topology on maps `M → N` ([Hirsch1976], §2.1) is
generated by the following sets. Fix a `C^n` map `f`, a chart of `M`, a compact set `K` of
coordinates in it, and a chart of `N` whose domain contains the image under `f` of the points with
coordinates in `K`. The set consists of the maps `g` with the same property whose chart expressions
have derivatives of order `k ≤ n` that are `ε`-close on `K` to those of `f`. A `BiChartWindow`
records the two charts and `K`, and `BiChartWindow.nbhdSet` is the generating set. On a compact
manifold the weak topology is the Whitney `C^n` topology.

The `C^n` diffeomorphisms `M ≃ₘ^n⟮I, J⟯ N` carry the induced topology. A generating set around a
diffeomorphism is a neighbourhood of it (`BiChartWindow.nbhdSet_mem_nhds`), so maps that are
first-order close on finitely many windows form a neighbourhood (`Diffeomorph.eventually_near`).
Conversely, uniform convergence of the chart derivatives on every window gives convergence
(`Diffeomorph.tendsto_nhds_of_tendstoUniformlyOn`).

## Main definitions

- `BiChartWindow`: a compact set of coordinates in a chart of `M` and a chart of `N`
- `BiChartWindow.MapsInto`, `BiChartWindow.expr`, `BiChartWindow.jet`
- `BiChartWindow.nbhdSet`: the generating sets of the weak topology
- `BiChartWindow.Near`: first-order closeness of two maps on a window
- `weakCnTopology`: the weak `C^n` topology on maps `M → N`
- `Diffeomorph.instTopologicalSpace`: the `C^n` topology on diffeomorphisms

## Main statements

- `BiChartWindow.continuousOn_jet`
- `BiChartWindow.nbhdSet_mem_nhds`
- `Diffeomorph.eventually_near`
- `Diffeomorph.tendsto_nhds_of_tendstoUniformlyOn`

## Implementation notes

The topology is defined on all maps `M → N`, with generating sets centred at `C^n` maps as in
[Hirsch1976]; its trace on `C^n` maps is the weak `C^n` topology of that reference, and the
diffeomorphisms carry the induced topology. Only the extended charts `extChartAt` of the given
atlases are used. There is no topology instance on `ContMDiffMap`, whose maps into a normed space
carry the topology of `JetTopology`.

## References

- [Hirsch1976]

## Tags

Whitney topology, weak topology, diffeomorphism, manifold
-/

open Set Filter Function Topology Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace ℝ E']
  {H' : Type*} [TopologicalSpace H'] {J : ModelWithCorners ℝ E' H'}
  {N : Type*} [TopologicalSpace N] [ChartedSpace H' N]

variable (I M J N) in
/-- A window for maps `M → N`: a compact set of coordinates in the extended chart of `M` at
`source`, compared through the extended chart of `N` at `target`. -/
structure BiChartWindow where
  /-- The point of `M` whose extended chart gives the coordinates. -/
  source : M
  /-- The point of `N` whose extended chart gives the values. -/
  target : N
  /-- The compact set of coordinates. -/
  set : Set E
  isCompact_set : IsCompact set
  set_subset : set ⊆ (extChartAt I source).target
  target_mem : target ∈ (extChartAt J target).source

namespace BiChartWindow

/-- The map `f` sends the points with coordinates in the window into the domain of the chart of
the target. -/
def MapsInto (w : BiChartWindow I M J N) (f : M → N) : Prop :=
  ∀ u ∈ w.set, f ((extChartAt I w.source).symm u) ∈ (extChartAt J w.target).source

/-- The expression of `f` in the two extended charts of the window. -/
noncomputable def expr (w : BiChartWindow I M J N) (f : M → N) : E → E' :=
  extChartAt J w.target ∘ f ∘ (extChartAt I w.source).symm

/-- The derivative of order `k` of the chart expression of `f`. -/
noncomputable def jet (w : BiChartWindow I M J N) (k : ℕ) (f : M → N) (u : E) :
    E [×k]→L[ℝ] E' :=
  iteratedFDeriv ℝ k (w.expr f) u

/-- The generating set of the weak topology: the maps that send the window into the chart of the
target and whose chart derivatives of order `k` are `ε`-close on the window to those of `f`. -/
def nbhdSet (w : BiChartWindow I M J N) (k : ℕ) (f : M → N) (ε : ℝ) : Set (M → N) :=
  {g | w.MapsInto g ∧ ∀ u ∈ w.set, dist (w.jet k g u) (w.jet k f u) < ε}

/-- `g` is `δ`-close to `f` to first order on the window: `g` sends the window into the chart of
the target, and the values and first derivatives of the chart expressions are `δ`-close. -/
def Near (w : BiChartWindow I M J N) (δ : ℝ) (g f : M → N) : Prop :=
  w.MapsInto g ∧ ∀ u ∈ w.set, dist (w.expr g u) (w.expr f u) < δ ∧
    dist (fderiv ℝ (w.expr g) u) (fderiv ℝ (w.expr f) u) < δ

/-- The jet of order `0` is the value of the chart expression. -/
theorem jet_zero (w : BiChartWindow I M J N) (f : M → N) (u : E) :
    w.jet 0 f u = (continuousMultilinearCurryFin0 ℝ E E').symm (w.expr f u) :=
  congrFun iteratedFDeriv_zero_eq_comp u

/-- The jet of order `1` is the derivative of the chart expression. -/
theorem jet_one (w : BiChartWindow I M J N) (f : M → N) (u : E) :
    w.jet 1 f u = (continuousMultilinearCurryFin1 ℝ E E').symm (fderiv ℝ (w.expr f) u) := by
  ext m
  rw [jet, iteratedFDeriv_one_apply, continuousMultilinearCurryFin1_symm_apply]

theorem dist_jet_zero (w : BiChartWindow I M J N) (g f : M → N) (u : E) :
    dist (w.jet 0 g u) (w.jet 0 f u) = dist (w.expr g u) (w.expr f u) := by
  rw [jet_zero, jet_zero, LinearIsometryEquiv.dist_map]

theorem dist_jet_one (w : BiChartWindow I M J N) (g f : M → N) (u : E) :
    dist (w.jet 1 g u) (w.jet 1 f u) = dist (fderiv ℝ (w.expr g) u) (fderiv ℝ (w.expr f) u) := by
  rw [jet_one, jet_one, LinearIsometryEquiv.dist_map]

/-- Closeness of the jets of orders `0` and `1` is first-order closeness. -/
theorem near_of_mem_nbhdSet {w : BiChartWindow I M J N} {δ : ℝ} {g f : M → N}
    (h₀ : g ∈ w.nbhdSet 0 f δ) (h₁ : g ∈ w.nbhdSet 1 f δ) : w.Near δ g f := by
  refine ⟨h₀.1, fun u hu ↦ ⟨?_, ?_⟩⟩
  · rw [← dist_jet_zero]
    exact h₀.2 u hu
  · rw [← dist_jet_one]
    exact h₁.2 u hu

theorem Near.mono {w : BiChartWindow I M J N} {δ δ' : ℝ} {g f : M → N} (h : w.Near δ g f)
    (hδ : δ ≤ δ') : w.Near δ' g f :=
  ⟨h.1, fun u hu ↦ ⟨(h.2 u hu).1.trans_le hδ, (h.2 u hu).2.trans_le hδ⟩⟩

/-- The jets of order at most `n` of a `C^n` map are continuous on a window it sends into the
chart of the target. -/
theorem continuousOn_jet [I.Boundaryless] {n : WithTop ℕ∞} [IsManifold I n M] [IsManifold J n N]
    (w : BiChartWindow I M J N) {f : M → N} (hf : ContMDiff I J n f) (hw : w.MapsInto f)
    {k : ℕ} (hk : (k : WithTop ℕ∞) ≤ n) : ContinuousOn (w.jet k f) w.set := by
  have hO : IsOpen ((extChartAt I w.source).target ∩
      (extChartAt I w.source).symm ⁻¹' (f ⁻¹' (extChartAt J w.target).source)) :=
    (continuousOn_extChartAt_symm w.source).isOpen_inter_preimage
      (isOpen_extChartAt_target w.source)
      (hf.continuous.isOpen_preimage _ (isOpen_extChartAt_source w.target))
  have hcd : ContDiffOn ℝ n (w.expr f) ((extChartAt I w.source).target ∩
      (extChartAt I w.source).symm ⁻¹' (f ⁻¹' (extChartAt J w.target).source)) :=
    (contMDiff_iff.1 hf).2 w.source w.target
  have h := hcd.continuousOn_iteratedFDerivWithin hk hO.uniqueDiffOn
  exact (h.congr fun u hu ↦ (iteratedFDerivWithin_of_isOpen k hO hu).symm).mono
    fun u hu ↦ ⟨w.set_subset hu, hw u hu⟩

end BiChartWindow

variable (I M J N) in
/-- The generating sets of the weak `C^n` topology ([Hirsch1976], §2.1): the sets
`w.nbhdSet k f ε` for windows `w`, orders `k ≤ n`, `C^n` maps `f` sending `w` into the chart of its
target, and `ε > 0`. -/
def weakCnSubbasis (n : WithTop ℕ∞) : Set (Set (M → N)) :=
  {s | ∃ (w : BiChartWindow I M J N) (k : ℕ) (f : M → N) (ε : ℝ), (k : WithTop ℕ∞) ≤ n ∧
    ContMDiff I J n f ∧ w.MapsInto f ∧ 0 < ε ∧ s = w.nbhdSet k f ε}

variable (I M J N) in
/-- The weak `C^n` topology on maps `M → N`, generated by `weakCnSubbasis`. -/
@[instance_reducible]
def weakCnTopology (n : WithTop ℕ∞) : TopologicalSpace (M → N) :=
  TopologicalSpace.generateFrom (weakCnSubbasis I M J N n)

namespace Diffeomorph

variable {n : WithTop ℕ∞}

/-- **The `C^n` topology on diffeomorphisms**, induced from the weak `C^n` topology on maps. -/
instance instTopologicalSpace : TopologicalSpace (M ≃ₘ^n⟮I, J⟯ N) :=
  TopologicalSpace.induced (fun Φ ↦ (Φ : M → N)) (weakCnTopology I M J N n)

theorem nhds_eq_comap_coe (Φ : M ≃ₘ^n⟮I, J⟯ N) :
    𝓝 Φ = comap (fun Ψ : M ≃ₘ^n⟮I, J⟯ N ↦ (Ψ : M → N))
      (@nhds (M → N) (weakCnTopology I M J N n) Φ) :=
  nhds_induced (T := weakCnTopology I M J N n) _ _

end Diffeomorph

/-- A generating set of the weak topology around a diffeomorphism is a neighbourhood of it. -/
theorem BiChartWindow.nbhdSet_mem_nhds {n : WithTop ℕ∞} (Φ : M ≃ₘ^n⟮I, J⟯ N)
    {w : BiChartWindow I M J N} (hw : w.MapsInto Φ) {k : ℕ} (hk : (k : WithTop ℕ∞) ≤ n)
    {ε : ℝ} (hε : 0 < ε) :
    {Ψ : M ≃ₘ^n⟮I, J⟯ N | (Ψ : M → N) ∈ w.nbhdSet k Φ ε} ∈ 𝓝 Φ := by
  have hopen : IsOpen[weakCnTopology I M J N n] (w.nbhdSet k Φ ε) :=
    TopologicalSpace.isOpen_generateFrom_of_mem ⟨w, k, Φ, ε, hk, Φ.contMDiff, hw, hε, rfl⟩
  rw [Diffeomorph.nhds_eq_comap_coe]
  refine preimage_mem_comap (@IsOpen.mem_nhds (M → N) (weakCnTopology I M J N n) _ _ hopen ?_)
  refine ⟨hw, fun u _ ↦ ?_⟩
  rw [dist_self]
  exact hε

namespace Diffeomorph

variable {n : WithTop ℕ∞}

/-- **Neighbourhoods of a diffeomorphism.** For `1 ≤ n`, the `C^n` diffeomorphisms that are
`δ`-close to `Φ` to first order on finitely many windows sent by `Φ` into the charts of their
targets form a neighbourhood of `Φ`. -/
theorem eventually_near (hn : 1 ≤ n) (Φ : M ≃ₘ^n⟮I, J⟯ N) (W : Finset (BiChartWindow I M J N))
    (hW : ∀ w ∈ W, w.MapsInto Φ) {δ : ℝ} (hδ : 0 < δ) :
    ∀ᶠ Ψ in 𝓝 Φ, ∀ w ∈ W, w.Near δ Ψ Φ := by
  rw [eventually_all_finset]
  intro w hw
  have h₀ : ((0 : ℕ) : WithTop ℕ∞) ≤ n := by
    rw [Nat.cast_zero]
    exact zero_le
  have h₁ : ((1 : ℕ) : WithTop ℕ∞) ≤ n := by
    rw [Nat.cast_one]
    exact hn
  filter_upwards [BiChartWindow.nbhdSet_mem_nhds Φ (hW w hw) h₀ hδ,
    BiChartWindow.nbhdSet_mem_nhds Φ (hW w hw) h₁ hδ] with Ψ hΨ₀ hΨ₁
  exact BiChartWindow.near_of_mem_nbhdSet hΨ₀ hΨ₁

/-- **Convergence of diffeomorphisms.** Suppose that every window sent by `Φ` into the chart of
its target is eventually sent there by `F p`, and that on each such window the chart derivatives of
order `k ≤ n` of `F p` converge uniformly to those of `Φ`. Then `F p` tends to `Φ`. -/
theorem tendsto_nhds_of_tendstoUniformlyOn [I.Boundaryless] [IsManifold I n M] [IsManifold J n N]
    {ι : Type*} {l : Filter ι} {F : ι → M ≃ₘ^n⟮I, J⟯ N} {Φ : M ≃ₘ^n⟮I, J⟯ N}
    (hmaps : ∀ w : BiChartWindow I M J N, w.MapsInto Φ → ∀ᶠ p in l, w.MapsInto (F p))
    (hjet : ∀ w : BiChartWindow I M J N, w.MapsInto Φ → ∀ k : ℕ, (k : WithTop ℕ∞) ≤ n →
      TendstoUniformlyOn (fun p ↦ w.jet k (F p)) (w.jet k Φ) l w.set) :
    Tendsto F l (𝓝 Φ) := by
  rw [Diffeomorph.nhds_eq_comap_coe, tendsto_comap_iff]
  refine TopologicalSpace.tendsto_nhds_generateFrom_iff.2 ?_
  rintro s ⟨w, k, f, ε, hk, hf, hwf, hε, rfl⟩ ⟨hwΦ, hΦ⟩
  -- The distance to the jets of `f` has a maximum smaller than `ε` on the window.
  have hcont : ContinuousOn (fun u ↦ dist (w.jet k Φ u) (w.jet k f u)) w.set :=
    (w.continuousOn_jet Φ.contMDiff hwΦ hk).dist (w.continuousOn_jet hf hwf hk)
  obtain ⟨δ, hδ, hδΦ⟩ : ∃ δ > 0, ∀ u ∈ w.set, dist (w.jet k Φ u) (w.jet k f u) + δ < ε := by
    rcases w.set.eq_empty_or_nonempty with h | h
    · exact ⟨1, one_pos, fun u hu ↦ by simp [h] at hu⟩
    · obtain ⟨u₁, hu₁, hmax⟩ := w.isCompact_set.exists_isMaxOn h hcont
      refine ⟨ε - dist (w.jet k Φ u₁) (w.jet k f u₁), sub_pos.2 (hΦ u₁ hu₁), fun u hu ↦ ?_⟩
      have hle : dist (w.jet k Φ u) (w.jet k f u) ≤ dist (w.jet k Φ u₁) (w.jet k f u₁) :=
        isMaxOn_iff.1 hmax u hu
      linarith
  filter_upwards [hmaps w hwΦ, Metric.tendstoUniformlyOn_iff.1 (hjet w hwΦ k hk) δ hδ]
    with p hp₁ hp₂
  refine ⟨hp₁, fun u hu ↦ ?_⟩
  have h₂ : dist (w.jet k (F p) u) (w.jet k Φ u) < δ := by
    rw [dist_comm]
    exact hp₂ u hu
  have h₃ := hδΦ u hu
  calc dist (w.jet k (F p) u) (w.jet k f u)
      ≤ dist (w.jet k (F p) u) (w.jet k Φ u) + dist (w.jet k Φ u) (w.jet k f u) :=
        dist_triangle _ _ _
    _ < ε := by linarith

end Diffeomorph
